# Generated by Django 4.1.5 on 2023-01-21 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_admin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='otp',
        ),
    ]
