# Generated by Django 4.1.5 on 2023-01-21 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_admin', '0002_remove_user_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP_Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.IntegerField(default=7812)),
                ('Email', models.EmailField(max_length=100)),
            ],
        ),
    ]
