# Generated by Django 4.1.5 on 2023-01-22 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_admin', '0014_productdetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductDetails',
        ),
    ]
